### ISSUE TITLE
4D5307F1 - Fable II

### ISSUE THREAD

**Issue by Metrichi** [xenia-canary/issue-dumpster#47]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [x] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/en-US/product/Fable-II/66acd000-77fe-1000-9115-d8024d5307f1

### Xenia version

https://github.com/xenia-project/xenia/commit/911055c44fd334a5f12d0ce28f7d70c88fb17fd1

### Issues

Some of the ground textures are not rendering properly on xenia_canary build and master build.
d3d12, Windows 10, rx580 with the latest driver (2023-08-31), i5 12400f, 16gb ddr4.
Personally I assume it has something to do with rx580 and AMD drivers.

### Log

[xenia.log.zip](https://github.com/xenia-canary/game-compatibility/files/12754559/xenia.log.zip)

### Screenshots

![xenia_canary_2023 09 28-23 24_1](https://github.com/xenia-canary/game-compatibility/assets/116955853/0a462638-e58b-48a5-a419-c9bf8a8c739a)
![unknown_2023 09 25-02 45](https://github.com/xenia-canary/game-compatibility/assets/116955853/a3bb492b-faab-443e-93e7-c62420081917)

### Labels

state-playable, gpu-drawing-corrupt

**Comment by Margen67** [comment]
Your issue is a duplicate.
